config/routes.rb
Ss::Application.routes.draw do

   

   
 

resources :articles do 
resources :comments
	end

 

root :to => 'articles#index'

end

app/models/advocate.rb
class Advocate < ActiveRecord::Base

  # attr_accessible :title, :body
has_many :advocate_services
end

app/models/article.rb
class Article < ActiveRecord::Base
has_many :comments 
  validates :title, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # attr_accessible :title, :body
belongs_to :article
end

app/models/course.rb
class Course < ActiveRecord::Base
  # attr_accessible :title, :body
has_many :teaching_assistants, as: :ta_duty
end

app/models/data_file.rb
class DataFile < ActiveRecord::Base
  # attr_accessible :title, :body
def self.save(upload)
name=upload['datafile'].original_filename
directory="/home/krishna/"
path=File.join(directory,name)
File.open(path, "wp") { |f| f.write(upload['datafile'].read)}
  end
end

app/models/demo.rb
class Demo < ActiveRecord::Base
  attr_accessible :name,:gender_id,:address,:dob,:doj,:place_id,:email,:mob,:src,:dest,:status,:tno,:tname,:amt,:check,:prf,:idno,:mpay,:cno,:sno,:tickno
  belongs_to :gender
  after_destroy :log_destroy_action
  belongs_to :place
  validates  :email,:mob,:dest,:src,:sno,:tno,:status,:prf,:idno,:mpay ,:tickno, :presence=> true
  validates :sno,uniqueness: true, numericality: { only_integer: true }
  validates :email, format: /@/#{ with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
validates :name, length: { maximum: 30 }
   def log_destroy_action
    puts 'Article destroyed'
  end         
end

app/models/gender.rb
class Gender < ActiveRecord::Base
  attr_accessible :gender_type
  has_many :users
  has_many :reservations
  has_many :demos, dependent: :destroy
def Gender.default_gender_type
gen_type=['Male','Female','Unknown']
status= false
gen_type.each do |each_type|
gen = self.new(:gender_type=>each_type)
status = gen.save
end
puts status
end
end

app/models/lab.rb
class Lab < ActiveRecord::Base
  # attr_accessible :title, :body
has_many :teaching_assistants, as: :ta_duty
end

app/models/layorreport.rb
class Layorreport < ActiveRecord::Base
  attr_accessible :city, :exp, :layorcode, :layorname, :rate
has_many :layorservices
has_many :mainreports
def Layorreport.default_values
	self.create(:layorcode=>101,:layorname=>'jp',:city=>'Ban',:exp=>2,:rate=>3) 
	self.create(:layorcode=>102,:layorname=>'ranjith',:city=>'erode',:exp=>5,:rate=>4) 
	end
end

app/models/lowerdetail.rb
class Lowerdetail < ActiveRecord::Base
has_many :lowyerservicedetails
	def Lowerdetail.default_migration
	 filename = "#{Rails.root}/lib/csv/Lawyers_City_List_new3.csv"

     file=File.new(filename,"r")
     while (line = file.gets)
       columns = line.split("$") 
      
      self.create(:lowyer_code=>columns[0].to_s.chomp.strip.squeeze(" "),
      	:lowyer=>columns[1].to_s.chomp.strip.squeeze(" "),
      	:experience=>columns[2].to_i,
      	:city=>columns[3].to_s.chomp.strip.squeeze(" "),
      	:rate=>columns[4].to_f)
      end
  end

end

app/models/lreport.rb
class Lreport < ActiveRecord::Base
  attr_accessible :city, :exp, :layorcode, :layorname, :rate
has_many :lservices
end

app/models/lservice.rb
class Lservice < ActiveRecord::Base
  attr_accessible :charge, :servicecode, :servicename,:lreport_id
belongs_to :lreport
#validates  :servicecode,:servicename, :presence=>true
validates :servicecode,:uniqueness=>true
end

app/models/main.rb
class Main < ActiveRecord::Base
  attr_accessible :city
end

app/models/mainreport.rb
class Mainreport < ActiveRecord::Base
  attr_accessible :city, :servicename,:layorservice_id,:layorreport_id
belongs_to :layorservice
belongs_to :layorreport
end

app/models/place.rb
class Place < ActiveRecord::Base
  attr_accessible :dest, :src
   has_many :demos
def Place.default_src
s_type=["Salem","Bangalore","Tuticorin","Erode","Mysore","Trichy","Coimbatore","ChennaiEgmore","Trissur","Kottayam","Alapuzha","Kanniyakumari","Namakkal","cochin","Palagatt","Madurai","Karur","Trivendram","Mangalore","Khazarcode","Tirupati","Mumbai"]
s_type.each do |each_type|
se=self.new(:src=>each_type)
s=se.save
end
puts s
end
def Place.default_dest
s_type=["Salem","Bangalore","Tuticorin","Erode","Mysore","Trichy","Coimbatore","ChennaiEgmore","Trissur","Kottayam","Alapuzha","Kanniyakumari","Namakkal","cochin","Palagatt","Madurai","Karur","Trivendram","Mangalore","Khazarcode","Tirupati","Mumbai"]
d_type.each do |each_type|
se=self.new(:dest=>each_type)
d=dn.save
end
puts d
end
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  attr_accessible :age, :availseats, :status, :destination, :doj, :gender, :nooFpass, :paddress, :pname, :sourse, :tname
   belongs_to :gender
  
def display_gender
gen_type=['Male','Female','Unknown']
range= false
gen_type.each do |each_type|
gen = self.new(:gender=>each_type)
range = gen.save
end
puts range
end


def display_status
st=["A/c","First","Second","sleeper","General"]
r=false
st.each do |each_type|
ss=self.new(:status=>each_type)
r=ss.save
end
puts r
end





def display_source
s_type=["Salem","Bangalore","Tuticorin","Erode","Mysore","Trichy","Coimbatore","ChennaiEgmore","Trissur","Kottayam","Alapuzha","Kanniyakumari","Namakkal","cochin","Palagatt","Madurai","Karur","Trivendram","Mangalore","Khazarcode","Tirupati","Mumbai"]
s=false
s_type.each do |each_type|
se=self.new(:source=>each_type)
s=se.save
end
puts s
end
def display_destination
s_type=["Salem","Bangalore","Tuticorin","Erode","Mysore","Trichy","Coimbatore","ChennaiEgmore","Trissur","Kottayam","Alapuzha","Kanniyakumari","Namakkal","cochin","Palagatt","Madurai","Karur","Trivendram","Mangalore","Khazarcode","Tirupati","Mumbai"]
d=false
d_type.each do |each_type|
se=self.new(:destination=>each_type)
d=dn.save
end
puts d
end
def display_tname
t_type=["YercaudExpress","BangaloreNagarcoilExpress","BrindavanExpress","cheranExpress","MysorebangaloreExp","Malaikottaiexp","CoimbatoreNagarcoilExp","ChennaiEgmoreExp","TataAlaphi","VeegalandExp","AlapuzhaExp","KanniyakumariEgmoreexp","Maduraikottayam","Guruvayurexp","PalagattExp","MeenakshiExp","Kaversuperpast","Trivendramsuperfast","MangaloreExp","sataptiExp","TirupatikanniyakumariExp","MumbaiCst","NellaiExp"]
t=false
t_type.each do |each_type|
tn=self.new(:tname=>each_type)
t=tn.save
end
puts t
end
end

app/models/student.rb
class Student < ActiveRecord::Base
  # attr_accessible :title, :body
def add
puts 'hai'
end
end
class Bca > Student
def sub 
puts 'hello'
end
end
class Mca > Student
def div
puts 'hello'
end
end

 

app/models/test.rb
class Test < ActiveRecord::Base
  attr_accessible :address, :name
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :address, :dob, :name,:gender_id
  belongs_to :gender
validates :address, presence: true
validates :name, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  http_basic_authenticate_with name: "krishna", password: "success", except: [:index, :show]

def new
 @article = Article.new
end

def edit
    @article = Article.find(params[:id])
  end

def update
    @article = Article.find(params[:id])
     @article.title = params[:article][:title]
     @article.body = params[:article][:body]
     @article.author = params[:article][:author]
if @article.save
      redirect_to @article
    else
      render 'edit'
    end
  end
 
def index
 @articles = Article.all
end

def create
  @article = Article.new()
@article.title = params[:article][:title]
@article.body = params[:article][:body]
@article.author = params[:article][:author]
#raise @article.inspect
if @article.save
    redirect_to :action =>'index'
  else
    render 'new'
  end
end

 def show

    @article = Article.find(params[:id])
  end

  
def destroy
    @article = Article.find(params[:id])
    @article.destroy

     redirect_to :action =>'index'
end
private
  def article_params
    params.require(:article).permit(:title, :body ,:author)
  end 
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
<p>
    <%= f.label :author %><br>
    <%= f.text_area :author %>
  </p>

 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
<th>Author</th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.body %></td>
      <td> <%= article.author %></td>
    <td><%= link_to 'show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'New article', new_article_path %>             

app/views/articles/new.html.erb
<h1>New article</h1>
<%= link_to 'Back', articles_path %>
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>
<p>
  <strong>Author:</strong>
  <%= @article.author %>
</p>

 <h2>Comments</h2>

<% @article.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>
<h2>Add a comment:</h2>
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>